### ISSUE TITLE
[Proposal] Use striking color for the `Keywords`.

### ISSUE THREAD

**Issue by ra1028** [cocopon/xcode-iceberg#1]
Hi ✋ 
Thanks for your cool color scheme.

However, visibility was not good in Xcode.
How about using more striking color for `Keywords` ?

**Comment by ra1028** [comment]
There’s one more thing.
I prefer to use the same color for `Other Class Names` and `Other type Names`.

**Comment by cocopon** [comment]
Thank you for your opinion!

> visibility was not good in Xcode

I applied the latest [Iceberg](https://github.com/cocopon/iceberg.vim/) palette (it's originally for Vim) in 152e638683e875b491c73613c95b3c9004164e95. Please try it.

> How about using more striking color for Keywords ?
> I prefer to use the same color for Other Class Names and Other type Names.

At the moment I think that the current coloration is okay. There are as many color preference as there are people. You can change them manually.

**Comment by ra1028** [comment]
@cocopon 
Thank you for your prompt response!
I pray that iceberg be loved by more people.
